// Authentication

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// once a user sends a request to LOGOUT, we expect it
// to be successful.
// We may need to check for whether the LOGOUT was successful
// so that we redirect to the LOGIN PAGE
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// Reset Password actions
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';

// for one Shopping list
export const CREATE_LIST_REQUEST = 'CREATE_LIST_REQUEST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILURE = 'CREATE_LIST_FAILURE';

export const VIEW_LIST_REQUEST = 'VIEW_LIST_REQUEST';
export const VIEW_LIST_SUCCESS = 'VIEW_LIST_SUCCESS';
export const VIEW_LIST_FAILURE = 'VIEW_LIST_FAILURE';

export const EDIT_LIST_REQUEST = 'EDIT_LIST_REQUEST';
export const EDIT_LIST_SUCCESS = 'EDIT_LIST_SUCCESS';
export const EDIT_LIST_FAILURE = 'EDIT_LIST_FAILURE';

export const DELETE_LIST_REQUEST = 'DELETE_LIST_REQUEST';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAILURE = 'DELETE_LIST_FAILURE';

// get many shopping lists
export const VIEW_ALL_LISTS_REQUEST = 'VIEW_ALL_LISTS_REQUEST';
export const VIEW_ALL_LISTS_SUCCESS = 'VIEW_ALL_LISTS_SUCCESS';
export const VIEW_ALL_LISTS_FAILURE = 'VIEW_ALL_LISTS_FAILURE';

// Shopping List Items
export const VIEW_ALL_ITEMS_REQUEST = 'VIEW_ALL_ITEMS_REQUEST';
export const VIEW_ALL_ITEMS_SUCCESS = 'VIEW_ALL_ITEMS_SUCCESS';
export const VIEW_ALL_ITEMS_FAILURE = 'VIEW_ALL_ITEMS_FAILURE';

export const CREATE_ITEM_REQUEST = 'CREATE_ITEM_REQUEST';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_FAILURE = 'CREATE_ITEM_FAILURE';

export const VIEW_ITEM_REQUEST = 'VIEW_ITEM_REQUEST';
export const VIEW_ITEM_SUCCESS = 'VIEW_ITEM_SUCCESS';
export const VIEW_ITEM_FAILURE = 'VIEW_ITEM_FAILURE';

export const EDIT_ITEM_REQUEST = 'EDIT_ITEM_REQUEST';
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS';
export const EDIT_ITEM_FAILURE = 'EDIT_ITEM_FAILURE';

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';

// SnackBar
export const DISPLAY_SNACK_BAR = 'DISPLAY_SNACK_BAR';
export const DISMISS_SNACK_BAR = 'DISMISS_SNACK_BAR';
